element.o: elem.h element.h elconcept.h elimpl.h arena.h
arena.o: elem.h element.h elconcept.h elimpl.h arena.h
workitem.o: elem.h element.h elconcept.h elimpl.h workitem.h
main.o: elem.h element.h elconcept.h elimpl.h arena.h workitem.h logging.h

